### ISSUE TITLE
MTC Adapter from Docker Image

### ISSUE THREAD

**Issue by rwuthric** [Demo-Smart-Factory-Concordia-University/OpenFactory#22]
Add the possibility to spin up an MTConnect adapter based on a Docker image. Syntax could be something along this:
```
zaix-001:
    UUID: ZAIX-001
    NODE: manager
    agent:
      PORT: 3001
      DEVICE_XML: ....
      adapter: 
        image: openfactory/adapter_image
        PORT: 7879
        environment:
          - MY_VAR=value
          - ...
```
This will attach to the network of the stack a Docker container created from the image and pass environment variables if desired. The created agent will then connect to the correct url of that docker container (needs to be changed in the code).
