### ISSUE TITLE
Add environment field in device yaml file

### ISSUE THREAD

**Issue by rwuthric** [Demo-Smart-Factory-Concordia-University/OpenFactory#26]
Some adapters require the definition of some environment variables. It must be possible to define them in the device yaml file which defines the configuration of a device requiring such an adapter built from a Docker image.

For example, like this:
```
devices:

  proximity-001:
    uuid: PROXIMITY-001
    node: manager
    agent:
      port: 3001
      device_xml: sensors/Proximity/imc30.xml
      adapter:
        image: ofa/sig350_adapter
        port: 7878
        environment:
          - SIG350_IP=10.0.0.250
          - DEVICE_ALIAS=master1port4
```
